import { props } from '@webflow/data-types'
import { declareComponent } from '@webflow/react'
import { webflowLayoutProps } from '../../shared/webflowLayoutProps'
import { MarqueeTitle } from './MarqueeTitle'

export default declareComponent(MarqueeTitle, {
  name: 'Marquee Title',
  description: 'Infinite lateral title marquee with ACG orange and nocturnal forest text.',
  group: 'ACG / Content',
  props: {
    text: props.Text({
      name: 'Text',
      defaultValue: 'How we work',
      group: 'Content',
    }),
    className: props.Text({
      name: 'Class Name',
      defaultValue: '',
      group: 'Layout',
      tooltip: 'Optional custom class applied to the outer component wrapper.',
    }),
    direction: props.Variant({
      name: 'Direction',
      options: ['Left', 'Right'],
      defaultValue: 'Left',
      group: 'Motion',
    }),
    speed: props.Number({
      name: 'Speed Seconds',
      defaultValue: 14,
      min: 1,
      max: 120,
      decimals: 1,
      group: 'Motion',
      tooltip: 'Animation duration in seconds. Lower values move faster.',
    }),
    edgeFade: props.Number({
      name: 'Edge Fade',
      defaultValue: 44,
      min: 0,
      max: 320,
      decimals: 0,
      group: 'Style',
      tooltip: 'Fade distance in pixels at each horizontal edge. Use 0 to disable.',
    }),
    fontSize: props.Number({
      name: 'Desktop Font Size',
      defaultValue: 40,
      min: 8,
      max: 240,
      decimals: 0,
      group: 'Typography',
    }),
    tabletFontSize: props.Number({
      name: 'Tablet Font Size',
      min: 8,
      max: 240,
      decimals: 0,
      group: 'Typography',
      tooltip: 'Optional. Falls back to desktop when empty.',
    }),
    mobileFontSize: props.Number({
      name: 'Mobile Font Size',
      min: 8,
      max: 240,
      decimals: 0,
      group: 'Typography',
      tooltip: 'Optional. Falls back to tablet, then desktop, when empty.',
    }),
    fontWeight: props.Number({
      name: 'Desktop Font Weight',
      defaultValue: 800,
      min: 100,
      max: 1000,
      decimals: 0,
      group: 'Typography',
    }),
    tabletFontWeight: props.Number({
      name: 'Tablet Font Weight',
      min: 100,
      max: 1000,
      decimals: 0,
      group: 'Typography',
      tooltip: 'Optional. Falls back to desktop when empty.',
    }),
    mobileFontWeight: props.Number({
      name: 'Mobile Font Weight',
      min: 100,
      max: 1000,
      decimals: 0,
      group: 'Typography',
      tooltip: 'Optional. Falls back to tablet, then desktop, when empty.',
    }),
    fontFamily: props.Text({
      name: 'Font Family',
      defaultValue: 'Ppneueyork, Georgia, serif',
      group: 'Typography',
    }),
    width: props.Number({
      name: 'Desktop Width',
      defaultValue: 720,
      min: 120,
      max: 2400,
      decimals: 0,
      group: 'Size',
    }),
    tabletWidth: props.Number({
      name: 'Tablet Width',
      min: 120,
      max: 2400,
      decimals: 0,
      group: 'Size',
      tooltip: 'Optional. Falls back to desktop when empty.',
    }),
    mobileWidth: props.Number({
      name: 'Mobile Width',
      min: 120,
      max: 2400,
      decimals: 0,
      group: 'Size',
      tooltip: 'Optional. Falls back to tablet, then desktop, when empty.',
    }),
    height: props.Number({
      name: 'Desktop Height',
      defaultValue: 120,
      min: 32,
      max: 600,
      decimals: 0,
      group: 'Size',
    }),
    tabletHeight: props.Number({
      name: 'Tablet Height',
      min: 32,
      max: 600,
      decimals: 0,
      group: 'Size',
      tooltip: 'Optional. Falls back to desktop when empty.',
    }),
    mobileHeight: props.Number({
      name: 'Mobile Height',
      min: 32,
      max: 600,
      decimals: 0,
      group: 'Size',
      tooltip: 'Optional. Falls back to tablet, then desktop, when empty.',
    }),
    textGap: props.Number({
      name: 'Text Gap',
      defaultValue: 12,
      min: 0,
      max: 240,
      decimals: 0,
      group: 'Size',
    }),
    ...webflowLayoutProps,
  },
})
