import { props } from '@webflow/data-types'
import { declareComponent } from '@webflow/react'
import { webflowLayoutProps } from '../../shared/webflowLayoutProps'
import { ACGMenuButton } from './ACGMenuButton'

export default declareComponent(ACGMenuButton, {
  name: 'ACG Menu Button',
  description: 'Standalone menu button that opens the fullscreen navigation menu with four configurable links.',
  group: 'ACG / Navigation',
  props: {
    variant: props.Variant({
      name: 'Variant',
      options: ['Button', 'Links To Button'],
      defaultValue: 'Button',
      group: 'Behavior',
    }),
    scrollTrigger: props.Number({
      name: 'Scroll Trigger',
      defaultValue: 24,
      min: 0,
      max: 5000,
      decimals: 0,
      group: 'Behavior',
      tooltip: 'Scroll position in pixels where the four links collapse into the menu button.',
    }),
    triggerAlignItems: props.Variant({
      name: 'Trigger Align Items',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    triggerJustifyItems: props.Variant({
      name: 'Trigger Justify Items',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    triggerAlignContent: props.Variant({
      name: 'Trigger Align Content',
      options: ['start', 'center', 'end', 'stretch', 'space-between'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    triggerJustifyContent: props.Variant({
      name: 'Trigger Justify Content',
      options: ['start', 'center', 'end', 'stretch', 'space-between'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    logoText: props.Text({
      name: 'Logo Text',
      defaultValue: 'Logo',
      group: 'Brand',
    }),
    menuLogo: props.Image({
      name: 'Open Menu Logo',
      group: 'Brand',
      tooltip: 'Logo shown in the center of the fullscreen menu header.',
    }),
    menuLogoHeight: props.Number({
      name: 'Open Menu Logo Height',
      defaultValue: 39,
      min: 8,
      max: 160,
      decimals: 0,
      group: 'Brand',
    }),
    hideOpenMenuLogo: props.Boolean({
      name: 'Hide Open Menu Logo',
      defaultValue: false,
      group: 'Brand',
    }),
    contactLabel: props.Text({
      name: 'Contact Label',
      defaultValue: 'GET IN TOUCH',
      group: 'Contact',
    }),
    contactLink: props.Link({
      name: 'Contact Link',
      group: 'Contact',
    }),
    contactColor: props.Text({
      name: 'Contact Color',
      defaultValue: 'var(--acg-color-nocturnal-forest, #152304)',
      group: 'Contact',
      tooltip: 'CSS color or variable for the Get In Touch button text and outline.',
    }),
    contactHoverColor: props.Text({
      name: 'Contact Hover Color',
      defaultValue: 'var(--acg-color-petal-mist, #F9F0ED)',
      group: 'Contact',
      tooltip: 'Hover color used inside the fullscreen menu.',
    }),
    menuLabel: props.Text({
      name: 'Menu Label',
      defaultValue: 'MENU',
      group: 'Controls',
    }),
    closeLabel: props.Text({
      name: 'Close Label',
      defaultValue: 'CLOSE',
      group: 'Controls',
    }),
    firstLabel: props.Text({
      name: 'First Label',
      defaultValue: 'WHAT WE DO',
      group: 'Links',
    }),
    firstLink: props.Link({
      name: 'First Link',
      group: 'Links',
    }),
    secondLabel: props.Text({
      name: 'Second Label',
      defaultValue: 'HOW WE WORK',
      group: 'Links',
    }),
    secondLink: props.Link({
      name: 'Second Link',
      group: 'Links',
    }),
    thirdLabel: props.Text({
      name: 'Third Label',
      defaultValue: 'WORK',
      group: 'Links',
    }),
    thirdLink: props.Link({
      name: 'Third Link',
      group: 'Links',
    }),
    fourthLabel: props.Text({
      name: 'Fourth Label',
      defaultValue: 'ABOUT',
      group: 'Links',
    }),
    fourthLink: props.Link({
      name: 'Fourth Link',
      group: 'Links',
    }),
    openMenuHeaderHeight: props.Number({
      name: 'Open Menu Header Height',
      defaultValue: 115,
      min: 64,
      max: 320,
      decimals: 0,
      group: 'Sizing',
    }),
    openMenuHeaderTopPadding: props.Number({
      name: 'Open Menu Header Top Padding',
      defaultValue: 28,
      min: 0,
      max: 120,
      decimals: 0,
      group: 'Sizing',
    }),
    menuBackground: props.Text({
      name: 'Menu Background',
      defaultValue: 'var(--acg-nav-menu-background, var(--acg-nav-background, var(--acg-color-signal-orange, #FF5A00)))',
      group: 'Variables',
    }),
    textColor: props.Text({
      name: 'Button Text Color',
      defaultValue: 'var(--acg-nav-text, var(--acg-color-nocturnal-forest, #152304))',
      group: 'Button Style',
    }),
    menuButtonHoverColor: props.Text({
      name: 'Button Hover Color',
      defaultValue: '',
      group: 'Button Style',
    }),
    menuButtonFontFamily: props.Text({
      name: 'Button Font Family',
      defaultValue: '',
      group: 'Button Style',
      tooltip: 'Optional CSS font-family. Leave empty to inherit.',
    }),
    menuButtonFontSize: props.Number({
      name: 'Button Font Size',
      defaultValue: 16,
      min: 8,
      max: 96,
      decimals: 0,
      group: 'Button Style',
    }),
    menuButtonFontWeight: props.Number({
      name: 'Button Font Weight',
      defaultValue: 900,
      min: 100,
      max: 1000,
      decimals: 0,
      group: 'Button Style',
    }),
    menuButtonLineHeight: props.Number({
      name: 'Button Line Height',
      defaultValue: 1,
      min: 0.7,
      max: 3,
      decimals: 2,
      group: 'Button Style',
    }),
    menuButtonLetterSpacing: props.Text({
      name: 'Button Letter Spacing',
      defaultValue: '0',
      group: 'Button Style',
    }),
    menuButtonTextTransform: props.Variant({
      name: 'Button Text Transform',
      options: ['none', 'uppercase', 'lowercase', 'capitalize'],
      defaultValue: 'none',
      group: 'Button Style',
    }),
    menuButtonAlignSelf: props.Variant({
      name: 'Button Align Self',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    menuButtonJustifySelf: props.Variant({
      name: 'Button Justify Self',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    linksColor: props.Text({
      name: 'Links Color',
      defaultValue: 'var(--acg-color-nocturnal-forest, #152304)',
      group: 'Initial Links Style',
    }),
    linksHoverColor: props.Text({
      name: 'Links Hover Color',
      defaultValue: 'var(--acg-color-signal-orange, #FF5A00)',
      group: 'Initial Links Style',
    }),
    linksFontFamily: props.Text({
      name: 'Links Font Family',
      defaultValue: '',
      group: 'Initial Links Style',
      tooltip: 'Optional CSS font-family. Leave empty to inherit.',
    }),
    linksFontSize: props.Number({
      name: 'Links Font Size',
      defaultValue: 14,
      min: 8,
      max: 96,
      decimals: 0,
      group: 'Initial Links Style',
    }),
    linksFontWeight: props.Number({
      name: 'Links Font Weight',
      defaultValue: 800,
      min: 100,
      max: 1000,
      decimals: 0,
      group: 'Initial Links Style',
    }),
    linksLetterSpacing: props.Text({
      name: 'Links Letter Spacing',
      defaultValue: '-0.06em',
      group: 'Initial Links Style',
    }),
    linksLineHeight: props.Number({
      name: 'Links Line Height',
      defaultValue: 1,
      min: 0.7,
      max: 3,
      decimals: 2,
      group: 'Initial Links Style',
    }),
    linksTextTransform: props.Variant({
      name: 'Links Text Transform',
      options: ['uppercase', 'none', 'lowercase', 'capitalize'],
      defaultValue: 'uppercase',
      group: 'Initial Links Style',
    }),
    linksGap: props.Number({
      name: 'Links Gap',
      defaultValue: 0,
      min: 0,
      max: 80,
      decimals: 0,
      group: 'Initial Links Style',
    }),
    linksAlignItems: props.Variant({
      name: 'Links Align Items',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    linksJustifyItems: props.Variant({
      name: 'Links Justify Items',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    linksAlignSelf: props.Variant({
      name: 'Links Align Self',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    linksJustifySelf: props.Variant({
      name: 'Links Justify Self',
      options: ['start', 'center', 'end', 'stretch'],
      defaultValue: 'start',
      group: 'Alignment',
    }),
    menuTextColor: props.Text({
      name: 'Menu Text Color',
      defaultValue: 'var(--acg-nav-menu-text, var(--acg-color-nocturnal-forest-50, rgba(21, 35, 4, 0.5)))',
      group: 'Variables',
    }),
    menuHoverColor: props.Text({
      name: 'Menu Hover Color',
      defaultValue: 'var(--acg-nav-menu-hover, var(--acg-color-nocturnal-forest, #152304))',
      group: 'Variables',
    }),
    ...webflowLayoutProps,
  },
})
