import { props } from '@webflow/data-types'
import { declareComponent } from '@webflow/react'
import { webflowLayoutProps } from '../../shared/webflowLayoutProps'
import { ACGNavbar } from './ACGNavbar'

export default declareComponent(ACGNavbar, {
  name: 'ACG Navbar',
  description: 'Sticky navbar with hero links, compact menu state, and fullscreen infinite menu.',
  group: 'ACG / Navigation',
  props: {
    logoText: props.Text({
      name: 'Logo Text',
      defaultValue: 'Logo',
      group: 'Brand',
    }),
    heroLogo: props.Image({
      name: 'Initial State Logo',
      group: 'Brand',
      tooltip: 'Logo used on the initial hero/orange navbar state.',
    }),
    heroLogoHeight: props.Number({
      name: 'Initial Logo Height',
      defaultValue: 39,
      min: 8,
      max: 160,
      decimals: 0,
      group: 'Brand',
    }),
    hideInitialLogo: props.Boolean({
      name: 'Hide Initial Logo',
      defaultValue: true,
      group: 'Brand',
      tooltip: 'Hide the logo in the first/orange navbar state.',
    }),
    compactLogo: props.Image({
      name: 'Scroll State Logo',
      group: 'Brand',
      tooltip: 'Logo used after scrolling, when the navbar becomes compact.',
    }),
    compactLogoHeight: props.Number({
      name: 'Scroll Logo Height',
      defaultValue: 39,
      min: 8,
      max: 160,
      decimals: 0,
      group: 'Brand',
    }),
    hideScrollLogo: props.Boolean({
      name: 'Hide Scroll Logo',
      defaultValue: false,
      group: 'Brand',
      tooltip: 'Hide the logo in the scrolled compact navbar state.',
    }),
    menuLogo: props.Image({
      name: 'Open Menu Logo',
      group: 'Brand',
      tooltip: 'Logo used inside the fullscreen open menu.',
    }),
    menuLogoHeight: props.Number({
      name: 'Open Menu Logo Height',
      defaultValue: 39,
      min: 8,
      max: 160,
      decimals: 0,
      group: 'Brand',
    }),
    hideOpenMenuLogo: props.Boolean({
      name: 'Hide Open Menu Logo',
      defaultValue: false,
      group: 'Brand',
      tooltip: 'Hide the logo inside the fullscreen open menu.',
    }),
    initialNavbarHeight: props.Number({
      name: 'Initial Navbar Height',
      defaultValue: 115,
      min: 64,
      max: 320,
      decimals: 0,
      group: 'Sizing',
      tooltip: 'Height in pixels for the first/orange navbar state.',
    }),
    scrollNavbarHeight: props.Number({
      name: 'Scroll Navbar Height',
      defaultValue: 92,
      min: 64,
      max: 320,
      decimals: 0,
      group: 'Sizing',
      tooltip: 'Height in pixels for the scrolled compact navbar state.',
    }),
    openMenuNavbarHeight: props.Number({
      name: 'Open Menu Navbar Height',
      defaultValue: 115,
      min: 64,
      max: 320,
      decimals: 0,
      group: 'Sizing',
      tooltip: 'Height in pixels for the header inside the fullscreen open menu.',
    }),
    initialNavbarTopPadding: props.Number({
      name: 'Initial Navbar Top Padding',
      defaultValue: 28,
      min: 0,
      max: 120,
      decimals: 0,
      group: 'Sizing',
      tooltip: 'Top padding in pixels for the first/orange navbar state.',
    }),
    scrollNavbarTopPadding: props.Number({
      name: 'Scroll Navbar Top Padding',
      defaultValue: 18,
      min: 0,
      max: 120,
      decimals: 0,
      group: 'Sizing',
      tooltip: 'Top padding in pixels for the scrolled compact navbar state.',
    }),
    openMenuNavbarTopPadding: props.Number({
      name: 'Open Menu Navbar Top Padding',
      defaultValue: 28,
      min: 0,
      max: 120,
      decimals: 0,
      group: 'Sizing',
      tooltip: 'Top padding in pixels for the fullscreen open menu header.',
    }),
    contactLabel: props.Text({
      name: 'Contact Label',
      defaultValue: 'GET IN TOUCH',
      group: 'Contact',
    }),
    contactLink: props.Link({
      name: 'Contact Link',
      group: 'Contact',
    }),
    contactColor: props.Text({
      name: 'Contact Color',
      defaultValue: 'var(--acg-color-nocturnal-forest, #152304)',
      group: 'Contact',
      tooltip: 'CSS color or variable for the Get In Touch button text and outline.',
    }),
    contactHoverColor: props.Text({
      name: 'Contact Hover Color',
      defaultValue: 'var(--acg-color-signal-orange, #FF5A00)',
      group: 'Contact',
      tooltip: 'Hover color used on the compact/light navbar state.',
    }),
    contactOrangeHoverColor: props.Text({
      name: 'Contact Orange Hover Color',
      defaultValue: 'var(--acg-color-petal-mist, #F9F0ED)',
      group: 'Contact',
      tooltip: 'Hover color used when the navbar or menu sits on the orange background.',
    }),
    menuLabel: props.Text({
      name: 'Menu Label',
      defaultValue: 'MENU',
      group: 'Controls',
    }),
    closeLabel: props.Text({
      name: 'Close Label',
      defaultValue: 'CLOSE',
      group: 'Controls',
    }),
    firstLabel: props.Text({
      name: 'First Label',
      defaultValue: 'WHAT WE DO',
      group: 'Links',
    }),
    firstLink: props.Link({
      name: 'First Link',
      group: 'Links',
    }),
    secondLabel: props.Text({
      name: 'Second Label',
      defaultValue: 'HOW WE WORK',
      group: 'Links',
    }),
    secondLink: props.Link({
      name: 'Second Link',
      group: 'Links',
    }),
    thirdLabel: props.Text({
      name: 'Third Label',
      defaultValue: 'WORK',
      group: 'Links',
    }),
    thirdLink: props.Link({
      name: 'Third Link',
      group: 'Links',
    }),
    fourthLabel: props.Text({
      name: 'Fourth Label',
      defaultValue: 'ABOUT',
      group: 'Links',
    }),
    fourthLink: props.Link({
      name: 'Fourth Link',
      group: 'Links',
    }),
    fifthLabel: props.Text({
      name: 'Fifth Label',
      defaultValue: '',
      group: 'Links',
      tooltip: 'Optional. Leave empty to hide this link.',
    }),
    fifthLink: props.Link({
      name: 'Fifth Link',
      group: 'Links',
    }),
    sixthLabel: props.Text({
      name: 'Sixth Label',
      defaultValue: '',
      group: 'Links',
      tooltip: 'Optional. Leave empty to hide this link.',
    }),
    sixthLink: props.Link({
      name: 'Sixth Link',
      group: 'Links',
    }),
    seventhLabel: props.Text({
      name: 'Seventh Label',
      defaultValue: '',
      group: 'Links',
      tooltip: 'Optional. Leave empty to hide this link.',
    }),
    seventhLink: props.Link({
      name: 'Seventh Link',
      group: 'Links',
    }),
    eighthLabel: props.Text({
      name: 'Eighth Label',
      defaultValue: '',
      group: 'Links',
      tooltip: 'Optional. Leave empty to hide this link.',
    }),
    eighthLink: props.Link({
      name: 'Eighth Link',
      group: 'Links',
    }),
    scrollThreshold: props.Number({
      name: 'Scroll Threshold',
      defaultValue: 24,
      min: 0,
      max: 240,
      decimals: 0,
      group: 'Behavior',
    }),
    logoRevealScroll: props.Number({
      name: 'Logo Reveal Scroll',
      min: 0,
      max: 5000,
      decimals: 0,
      group: 'Behavior',
      tooltip: 'Optional scroll position in pixels where the logo fades in. Leave empty or 0 to keep the logo visible by default.',
    }),
    navBackground: props.Text({
      name: 'Hero Background',
      defaultValue: 'var(--acg-nav-background, var(--acg-color-signal-orange, #FF5A00))',
      group: 'Variables',
      tooltip: 'CSS color or variable. Example: var(--acg-nav-background, var(--acg-color-signal-orange, #FF5A00)).',
    }),
    compactBackground: props.Text({
      name: 'Compact Background',
      defaultValue: 'var(--acg-nav-compact-background, var(--acg-color-petal-mist, #F9F0ED))',
      group: 'Variables',
      tooltip: 'CSS color or variable for the sticky compact state.',
    }),
    menuBackground: props.Text({
      name: 'Menu Background',
      defaultValue: 'var(--acg-nav-menu-background, var(--acg-nav-background, var(--acg-color-signal-orange, #FF5A00)))',
      group: 'Variables',
      tooltip: 'CSS color or variable for the fullscreen menu.',
    }),
    textColor: props.Text({
      name: 'Text Color',
      defaultValue: 'var(--acg-nav-text, var(--acg-color-nocturnal-forest, #152304))',
      group: 'Variables',
      tooltip: 'CSS color or variable for navbar text, CTA border, and CTA text.',
    }),
    menuTextColor: props.Text({
      name: 'Menu Text Color',
      defaultValue: 'var(--acg-nav-menu-text, var(--acg-color-nocturnal-forest-50, rgba(21, 35, 4, 0.5)))',
      group: 'Variables',
      tooltip: 'CSS color or variable for fullscreen menu links.',
    }),
    menuHoverColor: props.Text({
      name: 'Menu Hover Color',
      defaultValue: 'var(--acg-nav-menu-hover, var(--acg-color-nocturnal-forest, #152304))',
      group: 'Variables',
      tooltip: 'CSS color or variable for fullscreen menu link hover.',
    }),
    ...webflowLayoutProps,
  },
})
